all:
  name: Notify all
  description: Notify all
  fields:
    message:
      description: Notification content
      example: "Test Notification"
      required: true
      selector:
        text: {}
    title:
      description: Notification title
      example: "This is a test message"
      required: false
      selector:
        text: {}
    color:
      description: Message color
      example: "#c753e8"
      required: false
      selector:
        text: {}
    data:
      description: Other additional parameters
      example:
        image: "/local/image.png"
      required: false
      selector:
        object: {}

notify:
  name: Notify specific
  description: Notify specific
  fields:
    message:
      description: Notification content
      example: "Test Notification"
      required: true
      selector:
        text: {}
    targets:
      description: specified entry
      example: 
        - entryname1
        - entryname2
      required: true
      selector:
        object: {}
    title:
      description: Notification title
      example: "This is a test message"
      required: false
      selector:
        text: {}
    color:
      description: Message color
      example: "#c753e8"
      required: false
      selector:
        text: {}
    data:
      description: Other additional parameters
      example:
        image: "/local/image.png"
      required: false
      selector:
        object: {}
read:
  name: Read notification
  description: Read notification
  fields:
    targets:
      description: specified entry
      example: 
        - entryname1
        - entryname2
      required: true
      selector:
        object: {}
      
