send:
  name: Send notification
  description: Send notification
  fields:
    message:
      description: Notification content
      example: "Test Notification"
      required: true
      selector:
        text: {}
    title:
      description: Notification title
      example: "This is a test message"
      required: false
      selector:
        text: {}
    target:
      description: Device to receive notifications
      example: "mobile_app_my_phone"
      required: false
      selector:
        text: {}
    color:
      description: Message color
      example: "#c753e8"
      required: false
      selector:
        text: {}
    data:
      description: Other additional parameters
      example:
        image: "/local/image.png"
      required: false
      selector:
        object: {}

read:
  name: Read notification
  description: Read notification
  fields:
    target:
      description: The device to read notifications from
      example: "mobile_app_my_phone"
      required: true
      selector:
        text: {}

